apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: windturbine
    user: windturbine
    secureJsonData:
      password: changeme_in_production
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    editable: false
